spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native # only to be used for filesystem and classpath approach
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/jayesh014/microservice-config.git" # github url where all the conif files for all the microservices across all the env present
          default-label: main # default branch name inside the git repo
          timeout: 5 # wait for only 5 sec to connect  to github
          clone-on-start: true # clone the github repo while connecting during startup
          force-pull: true #override the local changes from the github repo
        #native:
          #search-locations: "file:///C://Users//jaybacha//Documents//eazybytes//config"
          #search-locations: "classpath:/config"
encrypt:
  key: "c7fd66839cd734beb38569447fc564977a60f940ee76f22b86e3d1f1cc18f911" # key used to encrypt and decrypt the properties info also exposing API for encrypt and decrypt
server:
  port:
    8071
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

